INSERT INTO USUARIO(LOGIN, SENHA) VALUES('admin','$2a$10$cJTVeATcVADIyKxyOPGTJ..cXzQxnH0OJ1OKkxl9EuXxgDR9XjUhG');
INSERT INTO PERMISSAO(PERMISSAO) VALUES('admin');
INSERT INTO USUARIO_PERMISSOES(USUARIO_LOGIN, PERMISSOES_PERMISSAO) VALUES('admin','admin');

INSERT INTO PRODUTO(ID, NOME, VALOR, DISPONIVEL) VALUES('3fa85f64-5717-4562-b3fc-2c963f66afa6', 'Caixa de Som', 2100.90, true);

